version: '3.8'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=romijulianto
      - POSTGRES_PASSWORD=romijulianto
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5434:5434'
volumes:
  postgres:
