BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[MmsVehicle] (
    [id] NVARCHAR(1000) NOT NULL,
    [plantCode] NVARCHAR(1000) NOT NULL,
    [ageOfVehicle] NVARCHAR(1000),
    [asuransiKadaluarsa] DATETIME2,
    [changeHeadTruck] NVARCHAR(1000),
    [compartment1Flow] BIT,
    [compartment2Flow] BIT,
    [compartment3Flow] BIT,
    [compartment4Flow] BIT,
    [compartment5Flow] BIT,
    [compartment6Flow] BIT,
    [contractInsuranceSchemeId] NVARCHAR(1000),
    [contractRateSchemeId] NVARCHAR(1000),
    [dateRegHeadTruck] DATETIME2,
    [deductibleInsurance] BIT,
    [grade] NVARCHAR(1000),
    [idTbbm] NVARCHAR(1000),
    [idTbbmPenempatan] NVARCHAR(1000),
    [idTruck] NVARCHAR(1000),
    [insuranceType] NVARCHAR(1000),
    [jenis] NVARCHAR(1000),
    [jeniskerjasama] NVARCHAR(1000),
    [jenissewaPenempatan] NVARCHAR(1000),
    [jenisusaha] NVARCHAR(1000),
    [jmlSegel] INT,
    [jmlSumbu] INT,
    [jumlahBan] INT,
    [jumlahKompartemen] INT,
    [kapasitas] NVARCHAR(1000),
    [kapasitasTangkiJalanBbm] FLOAT(53),
    [kapasitasTangkiJalanOli] FLOAT(53),
    [karoseri] BIT,
    [kelasBan] NVARCHAR(1000),
    [kepemilikan] NVARCHAR(1000),
    [ket] NVARCHAR(1000),
    [keterangan] NVARCHAR(1000),
    [ketersediaan] BIT,
    [keurKadaluarsa] DATETIME2,
    [kimImkKadaluarsa] DATETIME2,
    [kompartemen1Kepekaan] FLOAT(53),
    [kompartemen1RKosong] FLOAT(53),
    [kompartemen1TeraUlang] FLOAT(53),
    [kompartemen1Uom] FLOAT(53),
    [kompartemen1Vol] FLOAT(53),
    [kompartemen2Kepekaan] FLOAT(53),
    [kompartemen2RKosong] FLOAT(53),
    [kompartemen2TeraUlang] FLOAT(53),
    [kompartemen2Uom] FLOAT(53),
    [kompartemen2Vol] FLOAT(53),
    [kompartemen3Kepekaan] FLOAT(53),
    [kompartemen3RKosong] FLOAT(53),
    [kompartemen3TeraUlang] FLOAT(53),
    [kompartemen3Uom] FLOAT(53),
    [kompartemen3Vol] FLOAT(53),
    [kompartemen4Kepekaan] FLOAT(53),
    [kompartemen4RKosong] FLOAT(53),
    [kompartemen4TeraUlang] FLOAT(53),
    [kompartemen4Uom] FLOAT(53),
    [kompartemen4Vol] FLOAT(53),
    [kompartemen5Kepekaan] FLOAT(53),
    [kompartemen5RKosong] FLOAT(53),
    [kompartemen5TeraUlang] FLOAT(53),
    [kompartemen5Uom] FLOAT(53),
    [kompartemen5Vol] FLOAT(53),
    [kompartemen6Kepekaan] FLOAT(53),
    [kompartemen6RKosong] FLOAT(53),
    [kompartemen6TeraUlang] FLOAT(53),
    [kompartemen6Uom] FLOAT(53),
    [kompartemen6Vol] FLOAT(53),
    [loket] INT,
    [material] NVARCHAR(1000),
    [monthlyInsurance] NVARCHAR(1000),
    [monthlyRate] FLOAT(53),
    [mtCategory] INT,
    [mtKaroseri] NVARCHAR(1000),
    [mtScheme] NVARCHAR(1000),
    [noMesin] NVARCHAR(1000),
    [noPolisInsurance] NVARCHAR(1000),
    [penempatanActive] NVARCHAR(1000),
    [produkList] NVARCHAR(1000),
    [rangka] NVARCHAR(1000),
    [rasioOwnUseBbm] FLOAT(53),
    [refHeadTruck] NVARCHAR(1000),
    [region] NVARCHAR(1000),
    [sistemusaha] NVARCHAR(1000),
    [siupKadaluarsa] DATETIME2,
    [statusPenempatan] NVARCHAR(1000),
    [stnkKadaluarsa] DATETIME2,
    [tanggalPembuatan] DATETIME2,
    [tbbm] NVARCHAR(1000),
    [tbbmPenempatan] NVARCHAR(1000),
    [teraKadaluarsa] DATETIME2,
    [tipeMobil] NVARCHAR(1000),
    [transportir] NVARCHAR(1000),
    [vendorGps] NVARCHAR(1000),
    [insertDate] DATETIME2 NOT NULL CONSTRAINT [MmsVehicle_insertDate_df] DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT [MmsVehicle_pkey] PRIMARY KEY CLUSTERED ([id]),
    CONSTRAINT [MmsVehicle_id_key] UNIQUE NONCLUSTERED ([id])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
